#pragma once
//Constant hardcoded models for commonly used models

enum BlockModelType {
	BLOCK, CUSTOM, SLAB_TOP, SLAB_BOTTOM, SLAB_RIGHT, SLAB_LEFT, SLAB_FRONT, SLAB_BACK,
	SLOPE_UP_FRONT, SLOPE_UP_BACK, SLOPE_UP_RIGHT, SLOPE_UP_LEFT, SLOPE_DOWN_FRONT, SLOPE_DOWN_BACK, SLOPE_DOWN_RIGHT, SLOPE_DOWN_LEFT,
	SLAB1, SLAB2, SLAB3, SLAB4, SLAB5, SLAB6, SLAB7, SLAB9, SLAB10, SLAB11, SLAB12, SLAB13, SLAB14, SLAB15
};